version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/rust:latest
    working_directory: ~/catlang
    steps:
      - checkout
      - run:
          name: Install LLVM
          command: |
            sudo apt-get update
            sudo apt-get install -y lsb-release software-properties-common
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 10
      - run:
          name: Install nightly & stable
          command: |
            rustup install nightly
            rustup install stable
            rustup update
      - run:
          name: Install rustfmt
          command: rustup component add rustfmt
      - run:
          name: Install clippy
          command: rustup component add clippy
      - restore_cache:
          keys:
            - rust-mod-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: |
            cargo fmt --version
            cargo fmt --all -- --check
      - run:
          name: Lint
          command: |
            cargo clippy --version
            cargo clippy
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test --no-run
      - save_cache:
          key: rust-mod-v1-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
  code-coverage:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Pull xd009642/tarpaulin
          command: docker pull xd009642/tarpaulin:latest
      - run:
          name: Generate report
          command: >
            docker run --security-opt seccomp=unconfined -e CODECOV_TOKEN=${CODECOV_TOKEN}
            -v $PWD:/volume xd009642/tarpaulin sh -c "apt-get update && apt-get install -y lsb-release software-properties-common
            && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 10 && cargo tarpaulin -v
            --ciserver circle-ci --out Xml --all-features"
      - run:
          name: Upload
          command: bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "aszecsei@users.noreply.github.com"
            git config --global user.name "Alic Szecsei"
            echo "machine github.com login aszecsei password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=aszecsei npm run publish-gh-pages
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - code-coverage:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy-website:
          filters:
            branches:
              only:
                - master
