version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.1
      working_directory: /go/src/github.com/aszecsei/catlang
    steps:
      - checkout
      - run: go get -d github.com/magefile/mage
      - run: go run /go/src/github.com/magefile/mage/bootstrap.go install
      - run: go get -v -t -d ./...
      - run: go run mage.go test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build